### ISSUE TITLE
not connecting on xtream codes 2.91 and 2.92

### ISSUE THREAD

**Issue by AlbertEinsteinGlitchPoint** [zaclimon/Tsutaeru#7]
Hi not working for xtream codes 2.91 and 2.92   Your credentials are not valid

**Comment by zaclimon** [comment]
Tsutaeru checks if it can check a playlist from this type of links:

http://blah.com/get.php?username=blah&password=blah&type=m3u_plus&output=something

Does XtreamCodes 2.91/2.92 changes the layout for the URL's?

**Comment by AlbertEinsteinGlitchPoint** [comment]
Hi

i will generated the playlist like that and i can login via vlc player, and other apps.. i can also login using another app i have for testing xtream codes server, using same user login credentials it logs just fine on the other server.. will do further testing.

**Comment by AlbertEinsteinGlitchPoint** [comment]
i am confused, dos stream need to be in hls? because in xtream codes stream type is ffmpeg transcoded mpegts to mp4 acc.

i am looking into the code on the app it seems to force hls?

 val streamType = sharedPreferences?.getString(Constants.STREAM_TYPE_PREFERENCE, Constants.STREAM_TYPE_HLS)
        return getString(R.string.provider_playlist_url, url, username, password, streamType)

**Comment by AlbertEinsteinGlitchPoint** [comment]
in order to use on VLC i use this list format

http://ip.ip.ip.ip:25461/get.php?username=test&password=test&type=m3u_plus&output=mpegts

this way it loads the channels and epg together

**Comment by zaclimon** [comment]
Ahh yeah forgot about that. HLS is used by default for the streams. From what I understand, if HLS isn't enabled, it might not work correct?

Have you tried replacing your output by hls instead of mpegts in the url?

**Comment by zaclimon** [comment]
@AlbertEinsteinGlitchPoint Have you managed use HLS?

**Comment by AlbertEinsteinGlitchPoint** [comment]
Hi zaclimon

Sorry for late reply, as i have been busy at work with another project, and this tv project its just a hobbie on my spare time, so i have done some further testing, i have managed to get a amlogic s905 set top box running android TV OS custom, on lolipop 5.1 in order to make further testing, as prior i was justin the emulator on my android studio to test the app, and in the emulator i could not connect.  allways kept giving me wrong login credentials , login denied..


So first things first, i have compiled the debug app and installed in on the android lolipop 5.1 stb model for testing, when i input the domain ip,  user and password,  it allways throughs back to login denied , wrong credentials login,  but using another xtreams app on my pc using the same user,pass,ip,port i can login with no errors..  i have cable network, and wifi working on the set top box also, so i think its not a internet access issue.  have you ever had this problem, or can u replicate this kind of issue to find the error? it allways troughs me back to the login url screen.

**Comment by AlbertEinsteinGlitchPoint** [comment]
ok so i have made some further testing, using min sdk version to build on android studio i can install it on android 5.1 lolipop, but seems the network code is not working it  breaks it.

But running it on the emulator with build target sdk28 ,  running on emulator android 7.0 or 8.0 i get internet access , i can connect to the server , but cannot play the content stream cannot fetch the channels.

**Comment by zaclimon** [comment]
No problem. To be honest, I didn't check all the versions the last time I made an update since the main device I use it on runs on Android 8.0. If the networking code is the issue, maybe it could be fixable with other means. I would probably need to reproduce the issue in the emulator to be sure.

So far I didn't get the Live Channels app to work on newer revisions of Android so I mostly kept it with Android 6.0. (API 23) Last time I tried, I was able to connect to a provider and load channels from there as well.

**Comment by AlbertEinsteinGlitchPoint** [comment]
W/IInputConnectionWrapper: deleteSurroundingText on inactive InputConnection
                           commitText on inactive InputConnection
W/System.err: java.io.FileNotFoundException: http://ip.ip.ip.ip:25461/get.php?username=test&password=test&type=m3u_plus&output=hls
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:238)
                  at com.zaclimon.tsutaeru.util.NetworkUtils$Companion.getNetworkInputStream(NetworkUtils.kt:19)
                  at com.zaclimon.tsutaeru.ui.auth.AsyncAuthValidateInfo.doInBackground(AsyncAuthValidateInfo.kt:45)
                  at com.zaclimon.tsutaeru.ui.auth.AsyncAuthValidateInfo.doInBackground(AsyncAuthValidateInfo.kt:24)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                  at java.lang.Thread.run(Thread.java:818)
D/EGL_emulation: eglMakeCurrent: 0xaef93600: ver 3 0 (tinfo 0xaef92720)
V/RenderScript: 0xa2387000 Launching thread(s), CPUs 2
D/EGL_emulation: eglMakeCurrent: 0xaef93600: ver 3 0 (tinfo 0xaef92720)
E/Surface: getSlotFromBufferLocked: unknown buffer: 0xa2bdf360

**Comment by zaclimon** [comment]
Alright, after seeing this, it might be that HLS is not enabled on your end. In that case, try to change the line [there](https://github.com/zaclimon/Tsutaeru/blob/dev/app/src/main/java/com/zaclimon/tsutaeru/ui/auth/VerificationGuidedFragment.kt#L33) from `Constants.STREAM_TYPE_HLS` to `Constants.STREAM_TYPE_MPEG_TS`.

I didn't know that HLS wasn't activated by default even though MPEG_TS is the preferred format from Xtream Codes.

**Comment by AlbertEinsteinGlitchPoint** [comment]
Hi

ok will give it a try tomorrow on the android emulator

**Comment by zaclimon** [comment]
@AlbertEinsteinGlitchPoint Have you get anything working? I'll potentially close the issue if everything has been sorted out.

**Comment by AlbertEinsteinGlitchPoint** [comment]
Hi

unfortunately no luck, i am using a Set Top Box  with AndroidTV 5.1 lolipoop version, i cannot find AndroidTV firmware upgrade for my STB.. so i cannot connect on any server ip address, it seems to break the ethernet protocol when compiling, i also tested on the emulator for android 5.1 and the same thing happens..no internet access on it.  when trying to login on server allways gives the samer error  Wrong credentials.., i managed to login on AndroidTV emulator 6.0 or 8.0 not shure now done so many tests, but it does not fetch channels from the server.

**Comment by AlbertEinsteinGlitchPoint** [comment]
Hiya tested on androidtv 6.0 OS it connects sucess to server but does not download any channels or EPG, logged in with another app and it works fine on same xtream server  with same credentials.. i also tested compile the app on newer android versions 7,8 and it also connects to the server but it just keeps stuck on updating channels and does not download any channels or epg from the server.

**Comment by AlbertEinsteinGlitchPoint** [comment]
Hi zaclimon


i have tested differen x-tream codes servers vversions, 2.10 and 2.20 also..   using android tv OS  5.1,6.0,8.0  it all does the same thing, it connects sucessfull but when tried to update channels it says Content not available on VOD,  on settings, on info, user info i get ERROR the user info cannot be accessed...


EPG keeps stuck on % updating channels... very very ver strange i have tested about 8 different x-tream server versions.. and none worked, with other 3rd party app i can connect on all of them and download channel info, even using hls or mpeg_ts but on this android TV app nothing happens.... strange.. did you had time to check the app for testing, perhpas i could send u some sample test login for tryout on your side

**Comment by AlbertEinsteinGlitchPoint** [comment]
Ok it seems i have found the issue but i am now having troubles in changing the code 

basically i found the following on the log
 http://11.22.33.44:25461/get.php?username=test&password=test&type=m3u_plus&output=mpeg_ts

this seems to be the format used on the app, thats why its giving error credentials, because some x-tream servers are configured only with  type=m3u  and output=ts  

i did some test on one server today that i tried connecting with vlc using the output log data from tsutaeru app, and could not connect, so i changed the type and output to the ones mentioned and it connected, but now i am struggling to change this on the app code to do some testing

**Comment by AlbertEinsteinGlitchPoint** [comment]
06-04 00:57:48.819 3047-3074/com.zaclimon.tsutaeru W/System.err: java.io.FileNotFoundException: http://11.22.33.44:25461/get.php?username=teste&password=teste&type=m3u_plus&output=mpeg_ts

this is the error, but manually the file downloaded from x-tream server when i login is this file



this is the correct file downloaded from x-tream server.... below.. see the difference m3u_plus = m3u only and the mpeg_ts = ts 


http://11.22.33.44:25461/get.php?username=teste&password=teste&type=m3u&output=ts

**Comment by AlbertEinsteinGlitchPoint** [comment]
so aparently this has something to do with the stream_type

**Comment by AlbertEinsteinGlitchPoint** [comment]
Btw further testing i have changed in the services.xml a test on the mpeg_ts output which is allways failing the login.

and set it static  type=m3u&output=ts


i can now login to the server, but no live channels list get downloaded...

only show up the following screens

VOD

TV SERIES

TV CATCHUP

SETTINGS


but no live channels and on the log i can see i am logging in in the following format

Api Link: http://mikkm.xyz/android/androidApi.php?url=http:/examplesiteteste.comr:80/&mode=vod&username=test1&password=test1

**Comment by AlbertEinsteinGlitchPoint** [comment]
any ideas on what could be wrong????
